const test = require('node:test'), assert = require('node:assert/strict'), crypto = require('crypto');
const { createDb } = require('../lib/local-db');
const c = require('../../cloudfunctions/common/commerce');
process.env.APP_ENV='test'; process.env.PAYMENT_MODE='test';
const address={name:'测试',phone:'13800138000',province:'广东',city:'深圳',district:'南山',detail:'测试地址'};
function fixture(balance=0){return createDb({users:[{_id:'u',_openid:'buyer',balance}],products:[{_id:'p',name:'商品',status:'ON_SALE',sales:0}],product_skus:[{_id:'s',productId:'p',status:'ACTIVE',price:1000}],carts:[{_id:'cart',userId:'other',skuId:'s',count:1}]});}
const params=()=>({requestId:'request-1234567890',shippingAddress:address,items:[{skuId:'s',count:1,price:1}]});
async function paid(db){const r=await c.createOrder(db,'buyer',params());const o=await c.get(db,'orders',r.orderId);await c.confirmPayment(db,{orderId:o._id,totalFee:o.payAmount,openid:'buyer',transactionId:o.payAmount?'TEST_TX':`BALANCE_${o._id}`,isTest:true});return o;}
test('server prices and idempotent balance debit',async()=>{const db=fixture(500);const [a,b]=await Promise.all([c.createOrder(db,'buyer',params()),c.createOrder(db,'buyer',params())]);assert.equal(a.orderId,b.orderId);assert.equal(a.totalAmount,1000);assert.equal(a.payAmount,500);assert.equal(db.snapshot().users[0].balance,0);assert.equal(db.snapshot().balance_transactions.length,1);await assert.rejects(c.createOrder(db,'buyer',{...params(),items:[{skuId:'s',count:2}]}),{code:'IDEMPOTENCY_CONFLICT'});});
test('missing idempotency key and fractional amount rejected',async()=>{const db=fixture();await assert.rejects(c.createOrder(db,'buyer',{...params(),requestId:undefined}),{code:'INVALID_PARAMS'});await db.collection('product_skus').doc('s').update({data:{price:1.5}});await assert.rejects(c.createOrder(db,'buyer',params()),{code:'INVALID_PARAMS'});});
test('cart ownership failure rolls back order and balance',async()=>{const db=fixture(500);await assert.rejects(c.createOrder(db,'buyer',{...params(),items:[{skuId:'s',count:1,cartId:'cart'}]}),{code:'PERMISSION_DENIED'});assert.equal(db.snapshot().orders?.length||0,0);assert.equal(db.snapshot().users[0].balance,500);assert.equal(db.snapshot().carts.length,1);});
test('payment amount/buyer rejection and duplicate callback',async()=>{const db=fixture();const r=await c.createOrder(db,'buyer',params()),e={orderId:r.orderId,totalFee:1000,openid:'buyer',transactionId:'TX',isTest:true};await assert.rejects(c.confirmPayment(db,{...e,totalFee:1}),{code:'AMOUNT_MISMATCH'});await assert.rejects(c.confirmPayment(db,{...e,openid:'other'}),{code:'BUYER_MISMATCH'});await Promise.all([c.confirmPayment(db,e),c.confirmPayment(db,e)]);assert.equal(db.snapshot().payment_transactions.length,1);assert.equal(db.snapshot().products[0].sales,1);});
test('write failure rolls back payment state, sales and ledger',async()=>{const db=fixture();const r=await c.createOrder(db,'buyer',params());db.injectFailure((collection)=>collection==='payment_transactions');await assert.rejects(c.confirmPayment(db,{orderId:r.orderId,totalFee:1000,openid:'buyer',transactionId:'TX',isTest:true}));assert.equal((await c.get(db,'orders',r.orderId)).status,'PENDING_PAYMENT');assert.equal(db.snapshot().products[0].sales,0);});
test('cancel is idempotent and returns balance once',async()=>{const db=fixture(500);const r=await c.createOrder(db,'buyer',params());await assert.rejects(c.cancelOrder(db,{},r.orderId,'other'),{code:'ORDER_NOT_FOUND'});await Promise.all([c.cancelOrder(db,{},r.orderId,'buyer'),c.cancelOrder(db,{},r.orderId,'buyer')]);assert.equal(db.snapshot().users[0].balance,500);assert.equal(db.snapshot().balance_transactions.length,2);});
test('prepay lease excludes cancellation and duplicate prepay',async()=>{const db=fixture();const r=await c.createOrder(db,'buyer',params());await c.beginPayment(db,r.orderId,'buyer');await assert.rejects(c.cancelOrder(db,{},r.orderId,'buyer'),{code:'PAYMENT_BUSY'});await assert.rejects(c.beginPayment(db,r.orderId,'buyer'),{code:'PAYMENT_BUSY'});});
test('refund evidence required and cash/balance only returned once',async()=>{const db=fixture(500),o=await paid(db);await c.applyRefund(db,o._id,'buyer','不要了');const r=await c.beginRefund(db,o._id,'');await assert.rejects(c.finishRefund(db,r.refundNo),{code:'REFUND_EVIDENCE_INVALID'});const e={internal:true,status:'SUCCESS',out_refund_no:r.refundNo,out_trade_no:o.orderNo,amount:{total:500,refund:500,currency:'CNY'}};await assert.rejects(c.finishRefund(db,r.refundNo,{...e,amount:{...e.amount,refund:1000}}),{code:'REFUND_EVIDENCE_INVALID'});await Promise.all([c.finishRefund(db,r.refundNo,e),c.finishRefund(db,r.refundNo,e)]);assert.equal(db.snapshot().users[0].balance,500);assert.equal(db.snapshot().products[0].sales,0);});
test('shipped refund requires confirmed return, rejection preserves state',async()=>{const db=fixture(),o=await paid(db);await db.collection('orders').doc(o._id).update({data:{status:'SHIPPED'}});await c.applyRefund(db,o._id,'buyer','退货');await assert.rejects(c.beginRefund(db,o._id,''),{code:'RETURN_REQUIRED'});await c.rejectRefund(db,o._id,'等待退货');assert.equal((await c.get(db,'orders',o._id)).status,'SHIPPED');});
test('only active SUPER_ADMIN credentials and environment secret accepted',async()=>{process.env.ADMIN_JWT_SECRET='x'.repeat(40);const {createToken,permissionVersion}=require('../../cloudfunctions/common/crypto');const {requireAdmin}=require('../../cloudfunctions/common/authMiddleware');const db=createDb({admins:[{_id:'a',role:'MERCHANT',status:'ACTIVE',permissions:['*']}]});const a=await c.get(db,'admins','a');const token=createToken({adminId:'a',version:permissionVersion(a)});await assert.rejects(requireAdmin({token},db),{code:'ADMIN_REQUIRED'});delete process.env.ADMIN_JWT_SECRET;await assert.rejects(requireAdmin({token,adminJwtSecret:'x'.repeat(40)},db));assert.equal(process.env.ADMIN_JWT_SECRET,undefined);});
test('raw signature and AES-GCM notification verified, tampering rejected',()=>{const {privateKey,publicKey}=crypto.generateKeyPairSync('rsa',{modulusLength:2048,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}});Object.assign(process.env,{WECHAT_APP_ID:'wx-test',WECHAT_PAY_MCH_ID:'123',WECHAT_PAY_SERIAL_NO:'mch-serial',WECHAT_PAY_PRIVATE_KEY:privateKey,WECHAT_PAY_API_V3_KEY:'k'.repeat(32),WECHAT_PAY_PLATFORM_KEYS_JSON:JSON.stringify({'key-id':publicKey})});const g=require('../../cloudfunctions/common/payGateway'),nonce='123456789012',aad='transaction',cipher=crypto.createCipheriv('aes-256-gcm',Buffer.from('k'.repeat(32)),Buffer.from(nonce));cipher.setAAD(Buffer.from(aad));const ciphertext=Buffer.concat([cipher.update(JSON.stringify({out_trade_no:'order'})),cipher.final(),cipher.getAuthTag()]).toString('base64');const body=JSON.stringify({id:'event',event_type:'TRANSACTION.SUCCESS',resource:{algorithm:'AEAD_AES_256_GCM',nonce,associated_data:aad,ciphertext}}),timestamp=String(Math.floor(Date.now()/1000)),headers={'Wechatpay-Timestamp':timestamp,'Wechatpay-Nonce':'nonce','Wechatpay-Serial':'key-id','Wechatpay-Signature':crypto.sign('RSA-SHA256',Buffer.from(`${timestamp}\nnonce\n${body}\n`),privateKey).toString('base64')};assert.equal(g.decryptNotification({body,headers}).data.out_trade_no,'order');assert.throws(()=>g.decryptNotification({body:body+' ',headers}),{code:'SIGNATURE_INVALID'});assert.throws(()=>g.decryptNotification({body,headers:{...headers,'Wechatpay-Serial':'unknown'}}),{code:'SIGNATURE_INVALID'});});
